name: دریافت فایل اوبونتو

on:
  workflow_dispatch:  # اجرای دستی از طریق گیت‌هاب
  schedule:
    - cron: '0 0 * * 0'  # اجرای خودکار هر هفته

jobs:
  download-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: دریافت کدهای مخزن
        uses: actions/checkout@v4

      - name: دانلود فایل اوبونتو
        run: |
          mkdir -p ubuntu-files
          curl -L -o ubuntu-files/ubuntu-aarch64.tar.xz \
          https://github.com/termux/proot-distro/releases/download/v4.21.0/ubuntu-aarch64-pd-v4.21.0.tar.xz

      - name: commit و push کردن فایل به مخزن
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add ubuntu-files/
          git commit -m "افزودن فایل اوبونتو [skip ci]" || echo "تغییری برای commit وجود ندارد"
          git push